### PR TITLE
Move IndexWatcher logging level to debug

### PR DESCRIPTION
**Pull request by andrewbanchich**

### CODE REVIEW

**Comment by LucioFranco** [comment]
@andrewbanchich can you rebase this with master?

**Comment by andrewbanchich** [comment]
All set

**Comment by LucioFranco** [comment]
@andrewbanchich do you mind squashing your commits into one?

**Comment by hntd187** [comment]
@LucioFranco it's fine we can do it at merge point, he doesn't need to squash

**Pull request merged**
