### PR TITLE
Replace futures mpsc and oneshot by tokio-sync

### PR DESCRIPTION
**Pull request by mauri870**
The tokio team released the tokio-sync
crate which offers a mpsc and oneshot channel
analogous to the ones in the futures crate.

In some benchs, the new mpsc shows up to 7x improvement
over the futures version. The oneshot implementation
only provides a slight performance improvement, but when
updated to the std version of Future a much better
performance can be expected.

toshi-search#115

### CODE REVIEW

**Comment by hntd187** [comment]
I’d like to wait until the crate is published to merge this, we already have too many git deps and I wanna stablize this a bit

**Comment by LucioFranco** [comment]
@mauri870 the new version of tokio is now in toshi, you should be able to access it via `tokio::sync::*` and then we can merge this! Thanks.

**Comment by mauri870** [comment]
@LucioFranco This can be merged now

**Comment by mauri870** [comment]
@hntd187 Crossbeam channels are mpmc and tokio-sync only provides mpsc. Are you sure about this change? If so, what about the channels used in settings?

**Comment by hntd187** [comment]
Well that's no fun, I did not realize that okay then I guess we are not doing that then, this is good to go.

**Pull request merged**
